Fixed NME causing empty recent
java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.android.quickstep.TopTaskTracker$CachedTaskInfo.otherVisibleTaskThisIsExcludedOver(TopTaskTracker.java:256)