Fixed Unsupported error in A10
Lawnchair (Debug) bug report Dec 16, 2023 9:21:19 PM
version: 14 Dev (4276067) (13)
commit: 4276067
build.brand: Xiaomi
build.device: vince
build.display: QQ3A.200805.001
build.fingerprint: google/angler/angler:7.1.2/N2G47H/3783593:user/release-keys
build.hardware: qcom
build.id: QQ3A.200805.001
build.manufacturer: Xiaomi
build.model: Redmi 5 Plus
build.security.level: 2023-04-05
build.product: qassa_vince
build.type: user
version.codename: REL
version.incremental: 92d526381b
version.release: 10
version.sdk_int: 29
display.density_dpi: 440
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/work_mode_fab: Binary XML file line #45 in app.lawnchair.debug:layout/work_mode_fab: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/work_mode_fab: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0403cd a=4 r=0x7f06042e}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
	at android.widget.TextView.readTextAppearance(TextView.java:3966)
	at android.widget.TextView.<init>(TextView.java:1069)
	at android.widget.TextView.<init>(TextView.java:970)
	at android.widget.TextView.<init>(TextView.java:966)
	at app.lawnchair.LawnchairLayoutFactory$constructorMap$2.invoke(LawnchairLayoutFactory.kt:18)
	at app.lawnchair.LawnchairLayoutFactory$constructorMap$2.invoke(LawnchairLayoutFactory.kt:18)
	at app.lawnchair.LawnchairLayoutFactory.onCreateView(LawnchairLayoutFactory.kt:29)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1005)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:969)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1092)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at com.android.launcher3.allapps.WorkProfileManager.attachWorkModeSwitch(WorkProfileManager.java:174)
	at com.android.launcher3.allapps.WorkProfileManager.updateCurrentState(WorkProfileManager.java:158)
	at com.android.launcher3.allapps.WorkProfileManager.reset(WorkProfileManager.java:141)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.reset(ActivityAllAppsContainerView.java:502)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.reset(ActivityAllAppsContainerView.java:468)
	at com.android.launcher3.Launcher.onStateSetEnd(Launcher.java:1280)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onStateSetEnd(QuickstepLauncher.java:484)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onStateSetEnd(QuickstepLauncher.java:189)
	at com.android.launcher3.statemanager.StateManager.onStateTransitionEnd(StateManager.java:400)
	at com.android.launcher3.statemanager.StateManager.-$$Nest$monStateTransitionEnd(Unknown Source:0)
	at com.android.launcher3.statemanager.StateManager$1.onAnimationSuccess(StateManager.java:377)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(AnimationSuccessListener.java:40)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)