Fixed IllegalArgumentException: width & height must be > 0
Lawnchair (Debug) bug report Jan 23, 2024 01:35:38
version: 14 Dev (#365) (14)
commit: ab25769
build.brand: samsung
build.device: b2q
build.display: TP1A.220624.014.F711BXXS6FWK2
build.fingerprint: samsung/b2qxeea/b2q:13/TP1A.220624.014/F711BXXS6FWK2:user/release-keys
build.hardware: qcom
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-F711B
build.security.level: 2023-11-01
build.product: b2qxeea
build.type: user
version.codename: REL
version.incremental: F711BXXS6FWK2
version.release: 13
version.sdk_int: 33
display.density_dpi: 391
isRecentsEnabled: true

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: java.lang.IllegalArgumentException: width & height must be > 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4184)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4340)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalArgumentException: width & height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1300)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1277)
	at com.android.launcher3.icons.BitmapRenderer.createHardwareBitmap(BitmapRenderer.java:52)
	at com.android.launcher3.icons.ShadowGenerator$Builder.createPill(ShadowGenerator.java:151)
	at com.android.launcher3.icons.ShadowGenerator$Builder.createPill(ShadowGenerator.java:138)
	at com.android.launcher3.icons.DotRenderer.<init>(DotRenderer.java:78)
	at com.android.launcher3.DeviceProfile.createDotRenderer(DeviceProfile.java:726)
	at com.android.launcher3.DeviceProfile.<init>(DeviceProfile.java:708)
	at com.android.launcher3.DeviceProfile$Builder.build(DeviceProfile.java:2255)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:470)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:359)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:373)
	at com.android.launcher3.InvariantDeviceProfile.<init>(InvariantDeviceProfile.java:233)
	at com.android.launcher3.InvariantDeviceProfile.$r8$lambda$DNcXzmawjoq65q3wgQi9M48DryY(Unknown Source:2)
	at com.android.launcher3.InvariantDeviceProfile$$ExternalSyntheticLambda4.get(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$xtvr3aByNYHC2nsBQ97HC1SKg4A(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda0.get(Unknown Source:4)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:100)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
	at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:165)
	at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:111)
	at com.android.launcher3.LauncherAppState$$ExternalSyntheticLambda16.get(Unknown Source:2)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$xtvr3aByNYHC2nsBQ97HC1SKg4A(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda0.get(Unknown Source:4)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:100)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
	at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:99)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:519)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:578)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:215)
	at android.app.Activity.performCreate(Activity.java:8657)
	at android.app.Activity.performCreate(Activity.java:8636)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4165)
	... 12 more