fix NoClassDefFoundError 'ActivityTaskManager'
```
Lawnchair (Debug) bug report 6 de dez de 2023 13:43:28
version: 13 Dev (#27) (13)
commit: 83bc0e7
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ActivityTaskManager;
	at com.android.systemui.shared.system.ActivityManagerWrapper.<init>(ActivityManagerWrapper.java:73)
	at com.android.systemui.shared.system.ActivityManagerWrapper.<clinit>(ActivityManagerWrapper.java:64)
	at com.android.systemui.shared.system.ActivityManagerWrapper.getInstance(ActivityManagerWrapper.java:77)
	at com.android.launcher3.uioverrides.QuickstepLauncher.lambda$onUiChangedWhileSleeping$4(QuickstepLauncher.java:641)
	at com.android.launcher3.uioverrides.QuickstepLauncher.$r8$lambda$ZVdAVIwrbYvUMuRD15SAXpfHLb4(Unknown Source:0)
	at com.android.launcher3.uioverrides.QuickstepLauncher$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.ActivityTaskManager" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-H8HgEn3LbWYzNB49xdhOng==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-H8HgEn3LbWYzNB49xdhOng==/lib/arm, /data/app/app.lawnchair.debug-H8HgEn3LbWYzNB49xdhOng==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more

```